title = "RECAST group"
author = "RECAST Group" # changes the title on browser tabs
description = """
Instructional Systems &
Learning Technologies

Florida State University
"""
profilePicture = "images/d20.png"
keywords = "self-directed learning, culturally sustaining practices"
copyright = "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) {{ YEAR }}"

mainSecthuons = []
contentratio = 0.7
hidesidebar = false  # hidesd the sidebar on content pages
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
favicon = "favicons/favicon.ico"

customCss = ["css/syntax.css"]  # example ["css/custom.css"]
customJs = []  # example ["js/custom.js"]

# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/moqrnvdd"

# Google Fonts
googleFonts = [] # "Lato:wght@300;700", "Nanum+Myeongjo:wght@400;800", "Cutive+Mono"

#Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

singleDateFormat = "1/2/2006"
indexDateFormat = "1/2/2006"
listDateFormat = "1/2/2006"

# postSectionName = "news"

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"


## Social links
[[socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:bret.staudtwillet@fsu.edu"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/recastgroup/"
